version: '3.1'
services:
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3307"
    volumes:
      - davAnime_data:/var/lib/mysql
volumes:
  davAnime_data: